// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: diataxis/orderer.proto

package diataxis

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Streamed unordered Kubernetes manifest.
type OrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifest      []byte                 `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderRequest) Reset() {
	*x = OrderRequest{}
	mi := &file_diataxis_orderer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderRequest) ProtoMessage() {}

func (x *OrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diataxis_orderer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderRequest.ProtoReflect.Descriptor instead.
func (*OrderRequest) Descriptor() ([]byte, []int) {
	return file_diataxis_orderer_proto_rawDescGZIP(), []int{0}
}

func (x *OrderRequest) GetManifest() []byte {
	if x != nil {
		return x.Manifest
	}
	return nil
}

// Streamed ordered Kubernetes manifest.
type OrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifest      []byte                 `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderResponse) Reset() {
	*x = OrderResponse{}
	mi := &file_diataxis_orderer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResponse) ProtoMessage() {}

func (x *OrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diataxis_orderer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResponse.ProtoReflect.Descriptor instead.
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return file_diataxis_orderer_proto_rawDescGZIP(), []int{1}
}

func (x *OrderResponse) GetManifest() []byte {
	if x != nil {
		return x.Manifest
	}
	return nil
}

var File_diataxis_orderer_proto protoreflect.FileDescriptor

const file_diataxis_orderer_proto_rawDesc = "" +
	"\n" +
	"\x16diataxis/orderer.proto\x12\bdiataxis\"*\n" +
	"\fOrderRequest\x12\x1a\n" +
	"\bmanifest\x18\x01 \x01(\fR\bmanifest\"+\n" +
	"\rOrderResponse\x12\x1a\n" +
	"\bmanifest\x18\x01 \x01(\fR\bmanifest2N\n" +
	"\x0eOrdererService\x12<\n" +
	"\x05Order\x12\x16.diataxis.OrderRequest\x1a\x17.diataxis.OrderResponse(\x010\x01B Z\x1egithub.com/katastroma/diataxisb\x06proto3"

var (
	file_diataxis_orderer_proto_rawDescOnce sync.Once
	file_diataxis_orderer_proto_rawDescData []byte
)

func file_diataxis_orderer_proto_rawDescGZIP() []byte {
	file_diataxis_orderer_proto_rawDescOnce.Do(func() {
		file_diataxis_orderer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_diataxis_orderer_proto_rawDesc), len(file_diataxis_orderer_proto_rawDesc)))
	})
	return file_diataxis_orderer_proto_rawDescData
}

var file_diataxis_orderer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_diataxis_orderer_proto_goTypes = []any{
	(*OrderRequest)(nil),  // 0: diataxis.OrderRequest
	(*OrderResponse)(nil), // 1: diataxis.OrderResponse
}
var file_diataxis_orderer_proto_depIdxs = []int32{
	0, // 0: diataxis.OrdererService.Order:input_type -> diataxis.OrderRequest
	1, // 1: diataxis.OrdererService.Order:output_type -> diataxis.OrderResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_diataxis_orderer_proto_init() }
func file_diataxis_orderer_proto_init() {
	if File_diataxis_orderer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_diataxis_orderer_proto_rawDesc), len(file_diataxis_orderer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_diataxis_orderer_proto_goTypes,
		DependencyIndexes: file_diataxis_orderer_proto_depIdxs,
		MessageInfos:      file_diataxis_orderer_proto_msgTypes,
	}.Build()
	File_diataxis_orderer_proto = out.File
	file_diataxis_orderer_proto_goTypes = nil
	file_diataxis_orderer_proto_depIdxs = nil
}
