// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: diataxis/orderer.proto

package diataxis

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrdererService_OrderStream_FullMethodName = "/diataxis.OrdererService/OrderStream"
	OrdererService_Order_FullMethodName       = "/diataxis.OrdererService/Order"
)

// OrdererServiceClient is the client API for OrdererService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OrdererService sorts Kubernetes manifests by dependency.
type OrdererServiceClient interface {
	OrderStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[OrderStreamRequest, OrderStreamResponse], error)
	Order(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[OrderRequest, OrderResponse], error)
}

type ordererServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrdererServiceClient(cc grpc.ClientConnInterface) OrdererServiceClient {
	return &ordererServiceClient{cc}
}

func (c *ordererServiceClient) OrderStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[OrderStreamRequest, OrderStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OrdererService_ServiceDesc.Streams[0], OrdererService_OrderStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[OrderStreamRequest, OrderStreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrdererService_OrderStreamClient = grpc.BidiStreamingClient[OrderStreamRequest, OrderStreamResponse]

func (c *ordererServiceClient) Order(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[OrderRequest, OrderResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OrdererService_ServiceDesc.Streams[1], OrdererService_Order_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[OrderRequest, OrderResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrdererService_OrderClient = grpc.ClientStreamingClient[OrderRequest, OrderResponse]

// OrdererServiceServer is the server API for OrdererService service.
// All implementations must embed UnimplementedOrdererServiceServer
// for forward compatibility.
//
// OrdererService sorts Kubernetes manifests by dependency.
type OrdererServiceServer interface {
	OrderStream(grpc.BidiStreamingServer[OrderStreamRequest, OrderStreamResponse]) error
	Order(grpc.ClientStreamingServer[OrderRequest, OrderResponse]) error
	mustEmbedUnimplementedOrdererServiceServer()
}

// UnimplementedOrdererServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrdererServiceServer struct{}

func (UnimplementedOrdererServiceServer) OrderStream(grpc.BidiStreamingServer[OrderStreamRequest, OrderStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method OrderStream not implemented")
}
func (UnimplementedOrdererServiceServer) Order(grpc.ClientStreamingServer[OrderRequest, OrderResponse]) error {
	return status.Error(codes.Unimplemented, "method Order not implemented")
}
func (UnimplementedOrdererServiceServer) mustEmbedUnimplementedOrdererServiceServer() {}
func (UnimplementedOrdererServiceServer) testEmbeddedByValue()                        {}

// UnsafeOrdererServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrdererServiceServer will
// result in compilation errors.
type UnsafeOrdererServiceServer interface {
	mustEmbedUnimplementedOrdererServiceServer()
}

func RegisterOrdererServiceServer(s grpc.ServiceRegistrar, srv OrdererServiceServer) {
	// If the following call panics, it indicates UnimplementedOrdererServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrdererService_ServiceDesc, srv)
}

func _OrdererService_OrderStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OrdererServiceServer).OrderStream(&grpc.GenericServerStream[OrderStreamRequest, OrderStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrdererService_OrderStreamServer = grpc.BidiStreamingServer[OrderStreamRequest, OrderStreamResponse]

func _OrdererService_Order_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OrdererServiceServer).Order(&grpc.GenericServerStream[OrderRequest, OrderResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrdererService_OrderServer = grpc.ClientStreamingServer[OrderRequest, OrderResponse]

// OrdererService_ServiceDesc is the grpc.ServiceDesc for OrdererService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrdererService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "diataxis.OrdererService",
	HandlerType: (*OrdererServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OrderStream",
			Handler:       _OrdererService_OrderStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Order",
			Handler:       _OrdererService_Order_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "diataxis/orderer.proto",
}
